### ISSUE TITLE
Add Javadoc on many Spring Cloud Core project sites

### ISSUE THREAD

**Issue by dsiegal** [spring-cloud/spring-cloud-build#69] opened 2018-02-16 21:53 UTC
Go to the home page of [Spring Cloud Task](https://projects.spring.io/spring-cloud-task/) project. In the documentation table on the right, the API links points to the Javadoc for Spring Cloud Task. This is what I would expect.

Yet in most of the other Spring Cloud projects I've seen so far, the API links point to a wrong resource (either the the associated Github repo or the Reference documentation). For example, go to [Spring Cloud Security](https://cloud.spring.io/spring-cloud-security). The API links for releases 1.1.4, 1.1.5 and 1.2.1 point to the Github repo. The API links for 1.2.2 and 1.2.3 point to the Reference documentation. 
Similar behavior for (e.g. [Spring Cloud Config](https://cloud.spring.io/spring-cloud-config), [Spring Cloud Netflix](https://cloud.spring.io/spring-cloud-netflix/), [Spring Cloud AWS](https://cloud.spring.io/spring-cloud-aws/), etc.

The convention for working projects (throughout the Spring ecosystem) seems to be that javadoc is hosted at https://docs.spring.io/<project-name>, e.g.: https://docs.spring.io/spring-boot, https://docs.spring.io/spring-cloud-task. For the errant sites above, there is no such javadoc, e.g.: https://docs.spring.io/spring-cloud-config, https://docs.spring.io/spring-cloud-netflix, https://docs.spring.io/spring-cloud-aws, etc., all produce 404s.

It would be helpful if all spring projects generated and deployed javadoc to docs.spring.io, with correct links to them on their associated project sites.

**Comment by spencergibb** [comment] 2018-02-16 22:08
Spring Cloud Core projects (Build, Netflix, Commons, Config, Bus, Release, Aws, Cloudfoundry, Consul, Contract, Gateway, Security, Sleuth, Vault, Zookeeper, Pipelines) do not publish documents to http://docs.spring.io.

We're thinking of setting links to javadoc.io like this: https://www.javadoc.io/doc/org.springframework.cloud/spring-cloud-commons/1.2.3.RELEASE

Spring Cloud Task and Spring Cloud Stream are not part of core and have separate project teams, you'll need to submit separate issues there.

**Comment by garyrussell** [comment] 2018-02-17 23:25
[SC Task](https://cloud.spring.io/spring-cloud-task/) and [SC Stream](https://cloud.spring.io/spring-cloud-stream/) publish API artifacts already (like most Spring projects), so there is no need to open issues  for those projects.

**Comment by spencergibb** [comment] 2019-01-29 00:45
Duplicate of #42

**Closed by spencergibb** 2019-01-29 00:45 UTC
Labels: waiting-for-triage
